astra_777-1:
  cmd: astrad
  start-flags: "--trace"
  app-config:
    minimum-gas-prices: 0aastra
    index-events:
      - ethereum_tx.ethereumTxHash
    json-rpc:
      address: "0.0.0.0:26651"
      ws-address: "0.0.0.0:26652"
      api: "eth,net,web3,debug,astra"
  validators:
    - coins: 8000astra
      staked: 8000astra
    - coins: 2000astra
      staked: 2000astra
    - coins: 1000astra
      staked: 1000astra
  accounts:
    - name: team
      coins: 2222200000astra
  genesis:
    app_state:
      staking:
        params:
          bond_denom: "aastra"
          unbonding_time: "10s"
      gov:
        voting_params:
          voting_period: "10s"
        deposit_params:
          max_deposit_period: "10s"
          min_deposit:
            - denom: "aastra"
              amount: "10000000"